GET http://localhost:3001/

###

GET http://localhost:3001/users


###

POST http://localhost:3001/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "another user 6th",
    "email": "fakeEmail2@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3001/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "fakeEmail2@gmail.com",
    "password": "123456"
}